version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: express_db
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  express-app:
    image: moumou200/express-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      DB_HOST: mysql
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: express_db
    secrets:
      - db_user
      - db_password
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:

secrets:
  db_user:
    external: true
  db_password:
    external: true

